# based on: http://forum.oszone.net/thread-334713.html
$s = new-object -com 'internetexplorer.application'
$s.visible = $true
$target_url = 'https://tickets.fifa.com/Services/ADService.html?lang=ru'
$s.navigate2($target_url)
while (($s.Busy -eq $true ) -or ($s.ReadyState -ne 4)) {
  start-sleep 100
}
write-output $s.ReadyState # 4 a.k.a. READYSTATE_COMPLETE
write-output $s.Busy # False
$doc = $s.document ;
# $doc.documentElement;
# a lot of output
$m1 = $doc.documentElement.getElementsByClassName('header') ;
$m1 | foreach-object {
  $e1 = $_ ;
  # $e1 = $m1[1] ;
  write-output ( "Node name: " + $e1.nodeName );  # DIV
  # $e1.textContent ;  # ???? 02 - ?????? : ??????? - ????????????
  # $e1.parentNode ; # a lot of output
  $e2 = $e1.parentNode ;
  # $e2.innerHTML ;

  # <div class="header" ng-bind="product.productName">???? 02 -?????? : ??????? - ????????????</div>

  $e3 = $e2.parentNode;

  $e4 = $e3.NextSibling.NextSibling;

  # $e4.textContent ;
  #     CAT 1
  #     CAT 2
  #     CAT 3
  #     CAT 4

  $m2 = $e4.getElementsByClassName('categoryBox');
  # $m2[1];
  # $m2[1].innerHTML;
  # CAT 2
  # $m2[1].outerHTML
  # <div class="categoryBox zeroAvailability" ng-bind="cat.categoryName" ng-class="cat.availabilityColor">CAT 2</div>
  write-output $m2[0].outerHTML

  $m2 | where-object { $_.getAttribute('class') -match '.*zero.*' -or $_.getAttribute('class') -match '.*lowAvailability.*' } | foreach-object {
      write-output $_.outerHTML
  # $m2[1].getAttribute('ng-class')
  }
  # $m2[1].getAttribute('ng-class')
  # cat.availabilityColor
}
# TODO: https://stackoverflow.com/questions/3514945/running-a-javascript-function-in-an-instance-of-internet-explorer?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
# http://www.vbaexpress.com/forum/showthread.php?9690-Solved-call-a-javascript-function
$doc = $s.Document;
# [mshtml.IHTMLWindow2] $win = $doc.parentWindow
#
# [mshtml.IHTMLWindow2] $win = [mshtml.IHTMLWindow2]$doc.parentWindow
# Cannot convert the "System.__ComObject" value of type "System.__ComObject#{3050f55d-98b5-11cf-bb82-00aa00bdce0b}" to type "mshtml.IHTMLWindow2".
$doc.parentWindow.execScript("alert('Arbitrary javascript code')", "javascript");
# will pop up the Alert on IE

<#

$s.document | get-member

   TypeName: mshtml.HTMLDocumentClass

Name                                                MemberType Definition
----                                                ---------- ----------
HTMLDocumentEvents2_Event_onactivate                Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onafterupdate             Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onbeforeactivate          Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onbeforedeactivate        Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onbeforeeditfocus         Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onbeforeupdate            Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_oncellchange              Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onclick                   Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_oncontextmenu             Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_oncontrolselect           Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_ondataavailable           Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_ondatasetchanged          Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_ondatasetcomplete         Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_ondblclick                Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_ondeactivate              Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_ondragstart               Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onerrorupdate             Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onfocusin                 Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onfocusout                Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onhelp                    Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onkeydown                 Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onkeypress                Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onkeyup                   Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onmousedown               Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onmousemove               Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onmouseout                Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onmouseover               Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onmouseup                 Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onmousewheel              Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onpropertychange          Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onreadystatechange        Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onrowenter                Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onrowexit                 Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onrowsdelete              Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onrowsinserted            Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onselectionchange         Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onselectstart             Event      mshtml.HTMLDo...
HTMLDocumentEvents2_Event_onstop                    Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onactivate                 Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onafterupdate              Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onbeforeactivate           Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onbeforedeactivate         Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onbeforeeditfocus          Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onbeforeupdate             Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_oncellchange               Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onclick                    Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_oncontextmenu              Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_oncontrolselect            Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_ondataavailable            Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_ondatasetchanged           Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_ondatasetcomplete          Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_ondblclick                 Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_ondeactivate               Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_ondragstart                Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onerrorupdate              Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onfocusin                  Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onfocusout                 Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onhelp                     Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onkeydown                  Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onkeypress                 Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onkeyup                    Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onmousedown                Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onmousemove                Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onmouseout                 Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onmouseover                Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onmouseup                  Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onmousewheel               Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onpropertychange           Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onreadystatechange         Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onrowenter                 Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onrowexit                  Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onrowsdelete               Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onrowsinserted             Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onselectionchange          Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onselectstart              Event      mshtml.HTMLDo...
HTMLDocumentEvents_Event_onstop                     Event      mshtml.HTMLDo...
add_onactivate                                      Method     void add_onac...
add_onafterupdate                                   Method     void add_onaf...
add_onbeforeactivate                                Method     void add_onbe...
add_onbeforedeactivate                              Method     void add_onbe...
add_onbeforeeditfocus                               Method     void add_onbe...
add_onbeforeupdate                                  Method     void add_onbe...
add_oncellchange                                    Method     void add_once...
add_onclick                                         Method     void add_oncl...
add_oncontextmenu                                   Method     void add_onco...
add_oncontrolselect                                 Method     void add_onco...
add_ondataavailable                                 Method     void add_onda...
add_ondatasetchanged                                Method     void add_onda...
add_ondatasetcomplete                               Method     void add_onda...
add_ondblclick                                      Method     void add_ondb...
add_ondeactivate                                    Method     void add_onde...
add_ondragstart                                     Method     void add_ondr...
add_onerrorupdate                                   Method     void add_oner...
add_onfocusin                                       Method     void add_onfo...
add_onfocusout                                      Method     void add_onfo...
add_onhelp                                          Method     void add_onhe...
add_onkeydown                                       Method     void add_onke...
add_onkeypress                                      Method     void add_onke...
add_onkeyup                                         Method     void add_onke...
add_onmousedown                                     Method     void add_onmo...
add_onmousemove                                     Method     void add_onmo...
add_onmouseout                                      Method     void add_onmo...
add_onmouseover                                     Method     void add_onmo...
add_onmouseup                                       Method     void add_onmo...
add_onmousewheel                                    Method     void add_onmo...
add_onpropertychange                                Method     void add_onpr...
add_onreadystatechange                              Method     void add_onre...
add_onrowenter                                      Method     void add_onro...
add_onrowexit                                       Method     void add_onro...
add_onrowsdelete                                    Method     void add_onro...
add_onrowsinserted                                  Method     void add_onro...
add_onselectionchange                               Method     void add_onse...
add_onselectstart                                   Method     void add_onse...
add_onstop                                          Method     void add_onst...
appendChild                                         Method     mshtml.IHTMLD...
attachEvent                                         Method     bool attachEv...
clear                                               Method     void clear(),...
cloneNode                                           Method     mshtml.IHTMLD...
close                                               Method     void close(),...
createAttribute                                     Method     mshtml.IHTMLD...
createComment                                       Method     mshtml.IHTMLD...
createDocumentFragment                              Method     mshtml.IHTMLD...
createDocumentFromUrl                               Method     mshtml.IHTMLD...
createElement                                       Method     mshtml.IHTMLE...
CreateEventObject                                   Method     mshtml.IHTMLE...
CreateObjRef                                        Method     System.Runtim...
createRenderStyle                                   Method     mshtml.IHTMLR...
createStyleSheet                                    Method     mshtml.IHTMLS...
createTextNode                                      Method     mshtml.IHTMLD...
detachEvent                                         Method     void detachEv...
elementFromPoint                                    Method     mshtml.IHTMLE...
Equals                                              Method     bool Equals(S...
execCommand                                         Method     bool execComm...
execCommandShowHelp                                 Method     bool execComm...
FireEvent                                           Method     bool FireEven...
focus                                               Method     void focus(),...
getElementById                                      Method     mshtml.IHTMLE...
getElementsByName                                   Method     mshtml.IHTMLE...
getElementsByTagName                                Method     mshtml.IHTMLE...
GetHashCode                                         Method     int GetHashCo...
GetLifetimeService                                  Method     System.Object...
GetType                                             Method     type GetType()
hasChildNodes                                       Method     bool hasChild...
hasFocus                                            Method     bool hasFocus...
HTMLDocumentEvents2_Event_add_onactivate            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onafterupdate         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onbeforeactivate      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onbeforedeactivate    Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onbeforeeditfocus     Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onbeforeupdate        Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_oncellchange          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onclick               Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_oncontextmenu         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_oncontrolselect       Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_ondataavailable       Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_ondatasetchanged      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_ondatasetcomplete     Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_ondblclick            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_ondeactivate          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_ondragstart           Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onerrorupdate         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onfocusin             Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onfocusout            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onhelp                Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onkeydown             Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onkeypress            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onkeyup               Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onmousedown           Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onmousemove           Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onmouseout            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onmouseover           Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onmouseup             Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onmousewheel          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onpropertychange      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onreadystatechange    Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onrowenter            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onrowexit             Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onrowsdelete          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onrowsinserted        Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onselectionchange     Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onselectstart         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_add_onstop                Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onactivate         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onafterupdate      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onbeforeactivate   Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onbeforedeactivate Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onbeforeeditfocus  Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onbeforeupdate     Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_oncellchange       Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onclick            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_oncontextmenu      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_oncontrolselect    Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_ondataavailable    Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_ondatasetchanged   Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_ondatasetcomplete  Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_ondblclick         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_ondeactivate       Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_ondragstart        Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onerrorupdate      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onfocusin          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onfocusout         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onhelp             Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onkeydown          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onkeypress         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onkeyup            Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onmousedown        Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onmousemove        Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onmouseout         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onmouseover        Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onmouseup          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onmousewheel       Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onpropertychange   Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onreadystatechange Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onrowenter         Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onrowexit          Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onrowsdelete       Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onrowsinserted     Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onselectionchange  Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onselectstart      Method     void HTMLDocu...
HTMLDocumentEvents2_Event_remove_onstop             Method     void HTMLDocu...
IHTMLDocument2_clear                                Method     void IHTMLDoc...
IHTMLDocument2_close                                Method     void IHTMLDoc...
IHTMLDocument2_createElement                        Method     mshtml.IHTMLE...
IHTMLDocument2_createStyleSheet                     Method     mshtml.IHTMLS...
IHTMLDocument2_elementFromPoint                     Method     mshtml.IHTMLE...
IHTMLDocument2_execCommand                          Method     bool IHTMLDoc...
IHTMLDocument2_execCommandShowHelp                  Method     bool IHTMLDoc...
IHTMLDocument2_open                                 Method     System.Object...
IHTMLDocument2_queryCommandEnabled                  Method     bool IHTMLDoc...
IHTMLDocument2_queryCommandIndeterm                 Method     bool IHTMLDoc...
IHTMLDocument2_queryCommandState                    Method     bool IHTMLDoc...
IHTMLDocument2_queryCommandSupported                Method     bool IHTMLDoc...
IHTMLDocument2_queryCommandText                     Method     string IHTMLD...
IHTMLDocument2_queryCommandValue                    Method     System.Object...
IHTMLDocument2_toString                             Method     string IHTMLD...
IHTMLDocument2_write                                Method     void IHTMLDoc...
IHTMLDocument2_writeln                              Method     void IHTMLDoc...
IHTMLDocument3_attachEvent                          Method     bool IHTMLDoc...
IHTMLDocument3_createDocumentFragment               Method     mshtml.IHTMLD...
IHTMLDocument3_createTextNode                       Method     mshtml.IHTMLD...
IHTMLDocument3_detachEvent                          Method     void IHTMLDoc...
IHTMLDocument3_getElementById                       Method     mshtml.IHTMLE...
IHTMLDocument3_getElementsByName                    Method     mshtml.IHTMLE...
IHTMLDocument3_getElementsByTagName                 Method     mshtml.IHTMLE...
IHTMLDocument3_recalc                               Method     void IHTMLDoc...
IHTMLDocument3_releaseCapture                       Method     void IHTMLDoc...
IHTMLDocument4_createDocumentFromUrl                Method     mshtml.IHTMLD...
IHTMLDocument4_CreateEventObject                    Method     mshtml.IHTMLE...
IHTMLDocument4_createRenderStyle                    Method     mshtml.IHTMLR...
IHTMLDocument4_FireEvent                            Method     bool IHTMLDoc...
IHTMLDocument4_focus                                Method     void IHTMLDoc...
IHTMLDocument4_hasFocus                             Method     bool IHTMLDoc...
IHTMLDocument5_createAttribute                      Method     mshtml.IHTMLD...
IHTMLDocument5_createComment                        Method     mshtml.IHTMLD...
IHTMLDOMNode_appendChild                            Method     mshtml.IHTMLD...
IHTMLDOMNode_cloneNode                              Method     mshtml.IHTMLD...
IHTMLDOMNode_hasChildNodes                          Method     bool IHTMLDOM...
IHTMLDOMNode_insertBefore                           Method     mshtml.IHTMLD...
IHTMLDOMNode_removeChild                            Method     mshtml.IHTMLD...
IHTMLDOMNode_removeNode                             Method     mshtml.IHTMLD...
IHTMLDOMNode_replaceChild                           Method     mshtml.IHTMLD...
IHTMLDOMNode_replaceNode                            Method     mshtml.IHTMLD...
IHTMLDOMNode_swapNode                               Method     mshtml.IHTMLD...
InitializeLifetimeService                           Method     System.Object...
insertBefore                                        Method     mshtml.IHTMLD...
open                                                Method     System.Object...
queryCommandEnabled                                 Method     bool queryCom...
queryCommandIndeterm                                Method     bool queryCom...
queryCommandState                                   Method     bool queryCom...
queryCommandSupported                               Method     bool queryCom...
queryCommandText                                    Method     string queryC...
queryCommandValue                                   Method     System.Object...
recalc                                              Method     void recalc(b...
releaseCapture                                      Method     void releaseC...
removeChild                                         Method     mshtml.IHTMLD...
removeNode                                          Method     mshtml.IHTMLD...
remove_onactivate                                   Method     void remove_o...
remove_onafterupdate                                Method     void remove_o...
remove_onbeforeactivate                             Method     void remove_o...
remove_onbeforedeactivate                           Method     void remove_o...
remove_onbeforeeditfocus                            Method     void remove_o...
remove_onbeforeupdate                               Method     void remove_o...
remove_oncellchange                                 Method     void remove_o...
remove_onclick                                      Method     void remove_o...
remove_oncontextmenu                                Method     void remove_o...
remove_oncontrolselect                              Method     void remove_o...
remove_ondataavailable                              Method     void remove_o...
remove_ondatasetchanged                             Method     void remove_o...
remove_ondatasetcomplete                            Method     void remove_o...
remove_ondblclick                                   Method     void remove_o...
remove_ondeactivate                                 Method     void remove_o...
remove_ondragstart                                  Method     void remove_o...
remove_onerrorupdate                                Method     void remove_o...
remove_onfocusin                                    Method     void remove_o...
remove_onfocusout                                   Method     void remove_o...
remove_onhelp                                       Method     void remove_o...
remove_onkeydown                                    Method     void remove_o...
remove_onkeypress                                   Method     void remove_o...
remove_onkeyup                                      Method     void remove_o...
remove_onmousedown                                  Method     void remove_o...
remove_onmousemove                                  Method     void remove_o...
remove_onmouseout                                   Method     void remove_o...
remove_onmouseover                                  Method     void remove_o...
remove_onmouseup                                    Method     void remove_o...
remove_onmousewheel                                 Method     void remove_o...
remove_onpropertychange                             Method     void remove_o...
remove_onreadystatechange                           Method     void remove_o...
remove_onrowenter                                   Method     void remove_o...
remove_onrowexit                                    Method     void remove_o...
remove_onrowsdelete                                 Method     void remove_o...
remove_onrowsinserted                               Method     void remove_o...
remove_onselectionchange                            Method     void remove_o...
remove_onselectstart                                Method     void remove_o...
remove_onstop                                       Method     void remove_o...
replaceChild                                        Method     mshtml.IHTMLD...
replaceNode                                         Method     mshtml.IHTMLD...
swapNode                                            Method     mshtml.IHTMLD...
toString                                            Method     string toStri...
write                                               Method     void write(Pa...
writeln                                             Method     void writeln(...
activeElement                                       Property   mshtml.IHTMLE...
alinkColor                                          Property   System.Object...
all                                                 Property   mshtml.IHTMLE...
anchors                                             Property   mshtml.IHTMLE...
applets                                             Property   mshtml.IHTMLE...
attributes                                          Property   System.Object...
baseUrl                                             Property   string baseUr...
bgColor                                             Property   System.Object...
body                                                Property   mshtml.IHTMLE...
charset                                             Property   string charse...
childNodes                                          Property   System.Object...
compatMode                                          Property   string compat...
cookie                                              Property   string cookie...
defaultCharset                                      Property   string defaul...
designMode                                          Property   string design...
dir                                                 Property   string dir {g...
doctype                                             Property   mshtml.IHTMLD...
documentElement                                     Property   mshtml.IHTMLE...
domain                                              Property   string domain...
embeds                                              Property   mshtml.IHTMLE...
enableDownload                                      Property   bool enableDo...
expando                                             Property   bool expando ...
fgColor                                             Property   System.Object...
fileCreatedDate                                     Property   string fileCr...
fileModifiedDate                                    Property   string fileMo...
fileSize                                            Property   string fileSi...
fileUpdatedDate                                     Property   string fileUp...
firstChild                                          Property   mshtml.IHTMLD...
forms                                               Property   mshtml.IHTMLE...
frames                                              Property   mshtml.Frames...
IHTMLDocument2_activeElement                        Property   mshtml.IHTMLE...
IHTMLDocument2_alinkColor                           Property   System.Object...
IHTMLDocument2_all                                  Property   mshtml.IHTMLE...
IHTMLDocument2_anchors                              Property   mshtml.IHTMLE...
IHTMLDocument2_applets                              Property   mshtml.IHTMLE...
IHTMLDocument2_bgColor                              Property   System.Object...
IHTMLDocument2_body                                 Property   mshtml.IHTMLE...
IHTMLDocument2_charset                              Property   string IHTMLD...
IHTMLDocument2_cookie                               Property   string IHTMLD...
IHTMLDocument2_defaultCharset                       Property   string IHTMLD...
IHTMLDocument2_designMode                           Property   string IHTMLD...
IHTMLDocument2_domain                               Property   string IHTMLD...
IHTMLDocument2_embeds                               Property   mshtml.IHTMLE...
IHTMLDocument2_expando                              Property   bool IHTMLDoc...
IHTMLDocument2_fgColor                              Property   System.Object...
IHTMLDocument2_fileCreatedDate                      Property   string IHTMLD...
IHTMLDocument2_fileModifiedDate                     Property   string IHTMLD...
IHTMLDocument2_fileSize                             Property   string IHTMLD...
IHTMLDocument2_fileUpdatedDate                      Property   string IHTMLD...
IHTMLDocument2_forms                                Property   mshtml.IHTMLE...
IHTMLDocument2_frames                               Property   mshtml.Frames...
IHTMLDocument2_images                               Property   mshtml.IHTMLE...
IHTMLDocument2_lastModified                         Property   string IHTMLD...
IHTMLDocument2_linkColor                            Property   System.Object...
IHTMLDocument2_links                                Property   mshtml.IHTMLE...
IHTMLDocument2_location                             Property   mshtml.HTMLLo...
IHTMLDocument2_mimeType                             Property   string IHTMLD...
IHTMLDocument2_nameProp                             Property   string IHTMLD...
IHTMLDocument2_onafterupdate                        Property   System.Object...
IHTMLDocument2_onbeforeupdate                       Property   System.Object...
IHTMLDocument2_onclick                              Property   System.Object...
IHTMLDocument2_ondblclick                           Property   System.Object...
IHTMLDocument2_ondragstart                          Property   System.Object...
IHTMLDocument2_onerrorupdate                        Property   System.Object...
IHTMLDocument2_onhelp                               Property   System.Object...
IHTMLDocument2_onkeydown                            Property   System.Object...
IHTMLDocument2_onkeypress                           Property   System.Object...
IHTMLDocument2_onkeyup                              Property   System.Object...
IHTMLDocument2_onmousedown                          Property   System.Object...
IHTMLDocument2_onmousemove                          Property   System.Object...
IHTMLDocument2_onmouseout                           Property   System.Object...
IHTMLDocument2_onmouseover                          Property   System.Object...
IHTMLDocument2_onmouseup                            Property   System.Object...
IHTMLDocument2_onreadystatechange                   Property   System.Object...
IHTMLDocument2_onrowenter                           Property   System.Object...
IHTMLDocument2_onrowexit                            Property   System.Object...
IHTMLDocument2_onselectstart                        Property   System.Object...
IHTMLDocument2_parentWindow                         Property   mshtml.IHTMLW...
IHTMLDocument2_plugins                              Property   mshtml.IHTMLE...
IHTMLDocument2_protocol                             Property   string IHTMLD...
IHTMLDocument2_readyState                           Property   string IHTMLD...
IHTMLDocument2_referrer                             Property   string IHTMLD...
IHTMLDocument2_Script                               Property   System.Object...
IHTMLDocument2_scripts                              Property   mshtml.IHTMLE...
IHTMLDocument2_security                             Property   string IHTMLD...
IHTMLDocument2_selection                            Property   mshtml.IHTMLS...
IHTMLDocument2_styleSheets                          Property   mshtml.HTMLSt...
IHTMLDocument2_title                                Property   string IHTMLD...
IHTMLDocument2_url                                  Property   string IHTMLD...
IHTMLDocument2_vlinkColor                           Property   System.Object...
IHTMLDocument3_baseUrl                              Property   string IHTMLD...
IHTMLDocument3_childNodes                           Property   System.Object...
IHTMLDocument3_dir                                  Property   string IHTMLD...
IHTMLDocument3_documentElement                      Property   mshtml.IHTMLE...
IHTMLDocument3_enableDownload                       Property   bool IHTMLDoc...
IHTMLDocument3_inheritStyleSheets                   Property   bool IHTMLDoc...
IHTMLDocument3_onbeforeeditfocus                    Property   System.Object...
IHTMLDocument3_oncellchange                         Property   System.Object...
IHTMLDocument3_oncontextmenu                        Property   System.Object...
IHTMLDocument3_ondataavailable                      Property   System.Object...
IHTMLDocument3_ondatasetchanged                     Property   System.Object...
IHTMLDocument3_ondatasetcomplete                    Property   System.Object...
IHTMLDocument3_onpropertychange                     Property   System.Object...
IHTMLDocument3_onrowsdelete                         Property   System.Object...
IHTMLDocument3_onrowsinserted                       Property   System.Object...
IHTMLDocument3_onstop                               Property   System.Object...
IHTMLDocument3_parentDocument                       Property   mshtml.IHTMLD...
IHTMLDocument3_uniqueID                             Property   string IHTMLD...
IHTMLDocument4_media                                Property   string IHTMLD...
IHTMLDocument4_namespaces                           Property   System.Object...
IHTMLDocument4_oncontrolselect                      Property   System.Object...
IHTMLDocument4_onselectionchange                    Property   System.Object...
IHTMLDocument4_URLUnencoded                         Property   string IHTMLD...
IHTMLDocument5_compatMode                           Property   string IHTMLD...
IHTMLDocument5_doctype                              Property   mshtml.IHTMLD...
IHTMLDocument5_implementation                       Property   mshtml.IHTMLD...
IHTMLDocument5_onactivate                           Property   System.Object...
IHTMLDocument5_onbeforeactivate                     Property   System.Object...
IHTMLDocument5_onbeforedeactivate                   Property   System.Object...
IHTMLDocument5_ondeactivate                         Property   System.Object...
IHTMLDocument5_onfocusin                            Property   System.Object...
IHTMLDocument5_onfocusout                           Property   System.Object...
IHTMLDocument5_onmousewheel                         Property   System.Object...
IHTMLDOMNode2_ownerDocument                         Property   System.Object...
IHTMLDOMNode_attributes                             Property   System.Object...
IHTMLDOMNode_childNodes                             Property   System.Object...
IHTMLDOMNode_firstChild                             Property   mshtml.IHTMLD...
IHTMLDOMNode_lastChild                              Property   mshtml.IHTMLD...
IHTMLDOMNode_nextSibling                            Property   mshtml.IHTMLD...
IHTMLDOMNode_nodeName                               Property   string IHTMLD...
IHTMLDOMNode_nodeType                               Property   int IHTMLDOMN...
IHTMLDOMNode_nodeValue                              Property   System.Object...
IHTMLDOMNode_parentNode                             Property   mshtml.IHTMLD...
IHTMLDOMNode_previousSibling                        Property   mshtml.IHTMLD...
images                                              Property   mshtml.IHTMLE...
implementation                                      Property   mshtml.IHTMLD...
inheritStyleSheets                                  Property   bool inheritS...
lastChild                                           Property   mshtml.IHTMLD...
lastModified                                        Property   string lastMo...
linkColor                                           Property   System.Object...
links                                               Property   mshtml.IHTMLE...
location                                            Property   mshtml.HTMLLo...
media                                               Property   string media ...
mimeType                                            Property   string mimeTy...
nameProp                                            Property   string namePr...
namespaces                                          Property   System.Object...
nextSibling                                         Property   mshtml.IHTMLD...
nodeName                                            Property   string nodeNa...
nodeType                                            Property   int nodeType ...
nodeValue                                           Property   System.Object...
onactivate                                          Property   System.Object...
onafterupdate                                       Property   System.Object...
onbeforeactivate                                    Property   System.Object...
onbeforedeactivate                                  Property   System.Object...
onbeforeeditfocus                                   Property   System.Object...
onbeforeupdate                                      Property   System.Object...
oncellchange                                        Property   System.Object...
onclick                                             Property   System.Object...
oncontextmenu                                       Property   System.Object...
oncontrolselect                                     Property   System.Object...
ondataavailable                                     Property   System.Object...
ondatasetchanged                                    Property   System.Object...
ondatasetcomplete                                   Property   System.Object...
ondblclick                                          Property   System.Object...
ondeactivate                                        Property   System.Object...
ondragstart                                         Property   System.Object...
onerrorupdate                                       Property   System.Object...
onfocusin                                           Property   System.Object...
onfocusout                                          Property   System.Object...
onhelp                                              Property   System.Object...
onkeydown                                           Property   System.Object...
onkeypress                                          Property   System.Object...
onkeyup                                             Property   System.Object...
onmousedown                                         Property   System.Object...
onmousemove                                         Property   System.Object...
onmouseout                                          Property   System.Object...
onmouseover                                         Property   System.Object...
onmouseup                                           Property   System.Object...
onmousewheel                                        Property   System.Object...
onpropertychange                                    Property   System.Object...
onreadystatechange                                  Property   System.Object...
onrowenter                                          Property   System.Object...
onrowexit                                           Property   System.Object...
onrowsdelete                                        Property   System.Object...
onrowsinserted                                      Property   System.Object...
onselectionchange                                   Property   System.Object...
onselectstart                                       Property   System.Object...
onstop                                              Property   System.Object...
ownerDocument                                       Property   System.Object...
parentDocument                                      Property   mshtml.IHTMLD...
parentNode                                          Property   mshtml.IHTMLD...
parentWindow                                        Property   mshtml.IHTMLW...
plugins                                             Property   mshtml.IHTMLE...
previousSibling                                     Property   mshtml.IHTMLD...
protocol                                            Property   string protoc...
readyState                                          Property   string readyS...
referrer                                            Property   string referr...
Script                                              Property   System.Object...
scripts                                             Property   mshtml.IHTMLE...
security                                            Property   string securi...
selection                                           Property   mshtml.IHTMLS...
styleSheets                                         Property   mshtml.HTMLSt...
title                                               Property   string title ...
uniqueID                                            Property   string unique...
url                                                 Property   string url {g...
URLUnencoded                                        Property   string URLUne...
vlinkColor                                          Property   System.Object...



#>


<#
 $m1 | get-member

   TypeName: System.__ComObject#{3050f50c-98b5-11cf-bb82-00aa00bdce0b}

Name                         MemberType Definition
----                         ---------- ----------
addBehavior                  Method     int addBehavior (string, Variant)
addFilter                    Method     void addFilter (IUnknown)
appendChild                  Method     IHTMLDOMNode appendChild (IHTMLDOMNode)
applyElement                 Method     IHTMLElement applyElement (IHTMLElem...
attachEvent                  Method     bool attachEvent (string, IDispatch)
blur                         Method     void blur ()
clearAttributes              Method     void clearAttributes ()
click                        Method     void click ()
cloneNode                    Method     IHTMLDOMNode cloneNode (bool)
compareDocumentPosition      Method     ushort compareDocumentPosition (IHTM...
componentFromPoint           Method     string componentFromPoint (int, int)
contains                     Method     bool contains (IHTMLElement)
createControlRange           Method     IDispatch createControlRange ()
detachEvent                  Method     void detachEvent (string, IDispatch)
doScroll                     Method     void doScroll (Variant)
dragDrop                     Method     bool dragDrop ()
FireEvent                    Method     bool FireEvent (string, Variant)
focus                        Method     void focus ()
getAdjacentText              Method     string getAdjacentText (string)
getAttribute                 Method     Variant getAttribute (string, int)
getAttributeNode             Method     IHTMLDOMAttribute getAttributeNode (...
getAttributeNodeNS           Method     IHTMLDOMAttribute2 getAttributeNodeN...
getAttributeNS               Method     Variant getAttributeNS (Variant, str...
getBoundingClientRect        Method     IHTMLRect getBoundingClientRect ()
getClientRects               Method     IHTMLRectCollection getClientRects ()
getElementsByClassName       Method     IHTMLElementCollection getElementsBy...
getElementsByTagName         Method     IHTMLElementCollection getElementsBy...
getElementsByTagNameNS       Method     IHTMLElementCollection getElementsBy...
getExpression                Method     Variant getExpression (string)
hasAttribute                 Method     bool hasAttribute (string)
hasAttributeNS               Method     bool hasAttributeNS (Variant, string)
hasAttributes                Method     bool hasAttributes ()
hasChildNodes                Method     bool hasChildNodes ()
ie8_getAttribute             Method     Variant ie8_getAttribute (string)
ie8_getAttributeNode         Method     IHTMLDOMAttribute2 ie8_getAttributeN...
ie8_removeAttribute          Method     bool ie8_removeAttribute (string)
ie8_removeAttributeNode      Method     IHTMLDOMAttribute2 ie8_removeAttribu...
ie8_setAttribute             Method     void ie8_setAttribute (string, Variant)
ie8_setAttributeNode         Method     IHTMLDOMAttribute2 ie8_setAttributeN...
ie9_appendChild              Method     IHTMLDOMNode ie9_appendChild (IHTMLD...
ie9_getAttribute             Method     Variant ie9_getAttribute (string)
ie9_getAttributeNode         Method     IHTMLDOMAttribute2 ie9_getAttributeN...
ie9_hasAttribute             Method     bool ie9_hasAttribute (string)
ie9_hasAttributes            Method     bool ie9_hasAttributes ()
ie9_insertBefore             Method     IHTMLDOMNode ie9_insertBefore (IHTML...
ie9_removeAttribute          Method     void ie9_removeAttribute (string)
ie9_removeAttributeNode      Method     IHTMLDOMAttribute2 ie9_removeAttribu...
ie9_removeChild              Method     IHTMLDOMNode ie9_removeChild (IHTMLD...
ie9_replaceChild             Method     IHTMLDOMNode ie9_replaceChild (IHTML...
ie9_setAttribute             Method     void ie9_setAttribute (string, Variant)
ie9_setAttributeNode         Method     IHTMLDOMAttribute2 ie9_setAttributeN...
insertAdjacentElement        Method     IHTMLElement insertAdjacentElement (...
insertAdjacentHTML           Method     void insertAdjacentHTML (string, str...
insertAdjacentText           Method     void insertAdjacentText (string, str...
insertBefore                 Method     IHTMLDOMNode insertBefore (IHTMLDOMN...
isDefaultNamespace           Method     bool isDefaultNamespace (Variant)
isEqualNode                  Method     bool isEqualNode (IHTMLDOMNode3)
isSameNode                   Method     bool isSameNode (IHTMLDOMNode3)
isSupported                  Method     bool isSupported (string, Variant)
lookupNamespaceURI           Method     Variant lookupNamespaceURI (Variant)
lookupPrefix                 Method     Variant lookupPrefix (Variant)
mergeAttributes              Method     void mergeAttributes (IHTMLElement, ...
msMatchesSelector            Method     bool msMatchesSelector (string)
msReleasePointerCapture      Method     void msReleasePointerCapture (int)
msSetPointerCapture          Method     void msSetPointerCapture (int)
normalize                    Method     void normalize ()
querySelector                Method     IHTMLElement querySelector (string)
querySelectorAll             Method     IHTMLDOMChildrenCollection querySele...
releaseCapture               Method     void releaseCapture ()
removeAttribute              Method     bool removeAttribute (string, int)
removeAttributeNode          Method     IHTMLDOMAttribute removeAttributeNod...
removeAttributeNS            Method     void removeAttributeNS (Variant, str...
removeBehavior               Method     bool removeBehavior (int)
removeChild                  Method     IHTMLDOMNode removeChild (IHTMLDOMNode)
removeExpression             Method     bool removeExpression (string)
removeFilter                 Method     void removeFilter (IUnknown)
removeNode                   Method     IHTMLDOMNode removeNode (bool)
replaceAdjacentText          Method     string replaceAdjacentText (string, ...
replaceChild                 Method     IHTMLDOMNode replaceChild (IHTMLDOMN...
replaceNode                  Method     IHTMLDOMNode replaceNode (IHTMLDOMNode)
scrollIntoView               Method     void scrollIntoView (Variant)
setActive                    Method     void setActive ()
setAttribute                 Method     void setAttribute (string, Variant, ...
setAttributeNode             Method     IHTMLDOMAttribute setAttributeNode (...
setAttributeNodeNS           Method     IHTMLDOMAttribute2 setAttributeNodeN...
setAttributeNS               Method     void setAttributeNS (Variant, string...
setCapture                   Method     void setCapture (bool)
setExpression                Method     void setExpression (string, string, ...
swapNode                     Method     IHTMLDOMNode swapNode (IHTMLDOMNode)
toString                     Method     string toString ()
accessKey                    Property   string accessKey () {get} {set}
align                        Property   string align () {get} {set}
all                          Property   IDispatch all () {get}
ariaActivedescendant         Property   string ariaActivedescendant () {get}...
ariaBusy                     Property   string ariaBusy () {get} {set}
ariaChecked                  Property   string ariaChecked () {get} {set}
ariaControls                 Property   string ariaControls () {get} {set}
ariaDescribedby              Property   string ariaDescribedby () {get} {set}
ariaDisabled                 Property   string ariaDisabled () {get} {set}
ariaExpanded                 Property   string ariaExpanded () {get} {set}
ariaFlowto                   Property   string ariaFlowto () {get} {set}
ariaHaspopup                 Property   string ariaHaspopup () {get} {set}
ariaHidden                   Property   string ariaHidden () {get} {set}
ariaInvalid                  Property   string ariaInvalid () {get} {set}
ariaLabelledby               Property   string ariaLabelledby () {get} {set}
ariaLevel                    Property   short ariaLevel () {get} {set}
ariaLive                     Property   string ariaLive () {get} {set}
ariaMultiselectable          Property   string ariaMultiselectable () {get} ...
ariaOwns                     Property   string ariaOwns () {get} {set}
ariaPosinset                 Property   short ariaPosinset () {get} {set}
ariaPressed                  Property   string ariaPressed () {get} {set}
ariaReadonly                 Property   string ariaReadonly () {get} {set}
ariaRelevant                 Property   string ariaRelevant () {get} {set}
ariaRequired                 Property   string ariaRequired () {get} {set}
ariaSecret                   Property   string ariaSecret () {get} {set}
ariaSelected                 Property   string ariaSelected () {get} {set}
ariaSetsize                  Property   short ariaSetsize () {get} {set}
ariaValuemax                 Property   string ariaValuemax () {get} {set}
ariaValuemin                 Property   string ariaValuemin () {get} {set}
ariaValuenow                 Property   string ariaValuenow () {get} {set}
attributes                   Property   IDispatch attributes () {get}
behaviorUrns                 Property   IDispatch behaviorUrns () {get}
canHaveChildren              Property   bool canHaveChildren () {get}
canHaveHTML                  Property   bool canHaveHTML () {get}
childNodes                   Property   IDispatch childNodes () {get}
children                     Property   IDispatch children () {get}
className                    Property   string className () {get} {set}
clientHeight                 Property   int clientHeight () {get}
clientLeft                   Property   int clientLeft () {get}
clientTop                    Property   int clientTop () {get}
clientWidth                  Property   int clientWidth () {get}
constructor                  Property   IDispatch constructor () {get}
contentEditable              Property   string contentEditable () {get} {set}
currentStyle                 Property   IHTMLCurrentStyle currentStyle () {g...
dataFld                      Property   string dataFld () {get} {set}
dataFormatAs                 Property   string dataFormatAs () {get} {set}
dataSrc                      Property   string dataSrc () {get} {set}
dir                          Property   string dir () {get} {set}
disabled                     Property   bool disabled () {get} {set}
document                     Property   IDispatch document () {get}
filters                      Property   IHTMLFiltersCollection filters () {g...
firstChild                   Property   IHTMLDOMNode firstChild () {get}
hideFocus                    Property   bool hideFocus () {get} {set}
id                           Property   string id () {get} {set}
ie8_attributes               Property   IHTMLAttributeCollection3 ie8_attrib...
ie9_nodeName                 Property   string ie9_nodeName () {get}
ie9_tagName                  Property   string ie9_tagName () {get}
innerHTML                    Property   string innerHTML () {get} {set}
innerText                    Property   string innerText () {get} {set}
isContentEditable            Property   bool isContentEditable () {get}
isDisabled                   Property   bool isDisabled () {get}
isMultiLine                  Property   bool isMultiLine () {get}
isTextEdit                   Property   bool isTextEdit () {get}
lang                         Property   string lang () {get} {set}
language                     Property   string language () {get} {set}
lastChild                    Property   IHTMLDOMNode lastChild () {get}
localName                    Property   Variant localName () {get}
namespaceURI                 Property   Variant namespaceURI () {get}
nextSibling                  Property   IHTMLDOMNode nextSibling () {get}
nodeName                     Property   string nodeName () {get}
nodeType                     Property   int nodeType () {get}
nodeValue                    Property   Variant nodeValue () {get} {set}
noWrap                       Property   bool noWrap () {get} {set}
offsetHeight                 Property   int offsetHeight () {get}
offsetLeft                   Property   int offsetLeft () {get}
offsetParent                 Property   IHTMLElement offsetParent () {get}
offsetTop                    Property   int offsetTop () {get}
offsetWidth                  Property   int offsetWidth () {get}
onabort                      Property   Variant onabort () {get} {set}
onactivate                   Property   Variant onactivate () {get} {set}
onafterupdate                Property   Variant onafterupdate () {get} {set}
onbeforeactivate             Property   Variant onbeforeactivate () {get} {s...
onbeforecopy                 Property   Variant onbeforecopy () {get} {set}
onbeforecut                  Property   Variant onbeforecut () {get} {set}
onbeforedeactivate           Property   Variant onbeforedeactivate () {get} ...
onbeforeeditfocus            Property   Variant onbeforeeditfocus () {get} {...
onbeforepaste                Property   Variant onbeforepaste () {get} {set}
onbeforeupdate               Property   Variant onbeforeupdate () {get} {set}
onblur                       Property   Variant onblur () {get} {set}
oncanplay                    Property   Variant oncanplay () {get} {set}
oncanplaythrough             Property   Variant oncanplaythrough () {get} {s...
oncellchange                 Property   Variant oncellchange () {get} {set}
onchange                     Property   Variant onchange () {get} {set}
onclick                      Property   Variant onclick () {get} {set}
oncontextmenu                Property   Variant oncontextmenu () {get} {set}
oncontrolselect              Property   Variant oncontrolselect () {get} {set}
oncopy                       Property   Variant oncopy () {get} {set}
oncuechange                  Property   Variant oncuechange () {get} {set}
oncut                        Property   Variant oncut () {get} {set}
ondataavailable              Property   Variant ondataavailable () {get} {set}
ondatasetchanged             Property   Variant ondatasetchanged () {get} {s...
ondatasetcomplete            Property   Variant ondatasetcomplete () {get} {...
ondblclick                   Property   Variant ondblclick () {get} {set}
ondeactivate                 Property   Variant ondeactivate () {get} {set}
ondrag                       Property   Variant ondrag () {get} {set}
ondragend                    Property   Variant ondragend () {get} {set}
ondragenter                  Property   Variant ondragenter () {get} {set}
ondragleave                  Property   Variant ondragleave () {get} {set}
ondragover                   Property   Variant ondragover () {get} {set}
ondragstart                  Property   Variant ondragstart () {get} {set}
ondrop                       Property   Variant ondrop () {get} {set}
ondurationchange             Property   Variant ondurationchange () {get} {s...
onemptied                    Property   Variant onemptied () {get} {set}
onended                      Property   Variant onended () {get} {set}
onerror                      Property   Variant onerror () {get} {set}
onerrorupdate                Property   Variant onerrorupdate () {get} {set}
onfilterchange               Property   Variant onfilterchange () {get} {set}
onfocus                      Property   Variant onfocus () {get} {set}
onfocusin                    Property   Variant onfocusin () {get} {set}
onfocusout                   Property   Variant onfocusout () {get} {set}
onhelp                       Property   Variant onhelp () {get} {set}
oninput                      Property   Variant oninput () {get} {set}
oninvalid                    Property   Variant oninvalid () {get} {set}
onkeydown                    Property   Variant onkeydown () {get} {set}
onkeypress                   Property   Variant onkeypress () {get} {set}
onkeyup                      Property   Variant onkeyup () {get} {set}
onlayoutcomplete             Property   Variant onlayoutcomplete () {get} {s...
onload                       Property   Variant onload () {get} {set}
onloadeddata                 Property   Variant onloadeddata () {get} {set}
onloadedmetadata             Property   Variant onloadedmetadata () {get} {s...
onloadstart                  Property   Variant onloadstart () {get} {set}
onlosecapture                Property   Variant onlosecapture () {get} {set}
onmousedown                  Property   Variant onmousedown () {get} {set}
onmouseenter                 Property   Variant onmouseenter () {get} {set}
onmouseleave                 Property   Variant onmouseleave () {get} {set}
onmousemove                  Property   Variant onmousemove () {get} {set}
onmouseout                   Property   Variant onmouseout () {get} {set}
onmouseover                  Property   Variant onmouseover () {get} {set}
onmouseup                    Property   Variant onmouseup () {get} {set}
onmousewheel                 Property   Variant onmousewheel () {get} {set}
onmove                       Property   Variant onmove () {get} {set}
onmoveend                    Property   Variant onmoveend () {get} {set}
onmovestart                  Property   Variant onmovestart () {get} {set}
onmsanimationend             Property   Variant onmsanimationend () {get} {s...
onmsanimationiteration       Property   Variant onmsanimationiteration () {g...
onmsanimationstart           Property   Variant onmsanimationstart () {get} ...
onmsgesturechange            Property   Variant onmsgesturechange () {get} {...
onmsgesturedoubletap         Property   Variant onmsgesturedoubletap () {get...
onmsgestureend               Property   Variant onmsgestureend () {get} {set}
onmsgesturehold              Property   Variant onmsgesturehold () {get} {set}
onmsgesturestart             Property   Variant onmsgesturestart () {get} {s...
onmsgesturetap               Property   Variant onmsgesturetap () {get} {set}
onmsgotpointercapture        Property   Variant onmsgotpointercapture () {ge...
onmsinertiastart             Property   Variant onmsinertiastart () {get} {s...
onmslostpointercapture       Property   Variant onmslostpointercapture () {g...
onmsmanipulationstatechanged Property   Variant onmsmanipulationstatechanged...
onmspointercancel            Property   Variant onmspointercancel () {get} {...
onmspointerdown              Property   Variant onmspointerdown () {get} {set}
onmspointerhover             Property   Variant onmspointerhover () {get} {s...
onmspointermove              Property   Variant onmspointermove () {get} {set}
onmspointerout               Property   Variant onmspointerout () {get} {set}
onmspointerover              Property   Variant onmspointerover () {get} {set}
onmspointerup                Property   Variant onmspointerup () {get} {set}
onmstransitionend            Property   Variant onmstransitionend () {get} {...
onmstransitionstart          Property   Variant onmstransitionstart () {get}...
onpage                       Property   Variant onpage () {get} {set}
onpaste                      Property   Variant onpaste () {get} {set}
onpause                      Property   Variant onpause () {get} {set}
onplay                       Property   Variant onplay () {get} {set}
onplaying                    Property   Variant onplaying () {get} {set}
onprogress                   Property   Variant onprogress () {get} {set}
onpropertychange             Property   Variant onpropertychange () {get} {s...
onratechange                 Property   Variant onratechange () {get} {set}
onreadystatechange           Property   Variant onreadystatechange () {get} ...
onreset                      Property   Variant onreset () {get} {set}
onresize                     Property   Variant onresize () {get} {set}
onresizeend                  Property   Variant onresizeend () {get} {set}
onresizestart                Property   Variant onresizestart () {get} {set}
onrowenter                   Property   Variant onrowenter () {get} {set}
onrowexit                    Property   Variant onrowexit () {get} {set}
onrowsdelete                 Property   Variant onrowsdelete () {get} {set}
onrowsinserted               Property   Variant onrowsinserted () {get} {set}
onscroll                     Property   Variant onscroll () {get} {set}
onseeked                     Property   Variant onseeked () {get} {set}
onseeking                    Property   Variant onseeking () {get} {set}
onselect                     Property   Variant onselect () {get} {set}
onselectstart                Property   Variant onselectstart () {get} {set}
onstalled                    Property   Variant onstalled () {get} {set}
onsubmit                     Property   Variant onsubmit () {get} {set}
onsuspend                    Property   Variant onsuspend () {get} {set}
ontimeupdate                 Property   Variant ontimeupdate () {get} {set}
onvolumechange               Property   Variant onvolumechange () {get} {set}
onwaiting                    Property   Variant onwaiting () {get} {set}
outerHTML                    Property   string outerHTML () {get} {set}
outerText                    Property   string outerText () {get} {set}
ownerDocument                Property   IDispatch ownerDocument () {get}
parentElement                Property   IHTMLElement parentElement () {get}
parentNode                   Property   IHTMLDOMNode parentNode () {get}
parentTextEdit               Property   IHTMLElement parentTextEdit () {get}
prefix                       Property   Variant prefix () {get} {set}
previousSibling              Property   IHTMLDOMNode previousSibling () {get}
readyState                   Property   Variant readyState () {get}
recordNumber                 Property   Variant recordNumber () {get}
role                         Property   string role () {get} {set}
runtimeStyle                 Property   IHTMLStyle runtimeStyle () {get}
scopeName                    Property   string scopeName () {get}
scrollHeight                 Property   int scrollHeight () {get}
scrollLeft                   Property   int scrollLeft () {get} {set}
scrollTop                    Property   int scrollTop () {get} {set}
scrollWidth                  Property   int scrollWidth () {get}
sourceIndex                  Property   int sourceIndex () {get}
spellcheck                   Property   Variant spellcheck () {get} {set}
style                        Property   IHTMLStyle style () {get}
tabIndex                     Property   short tabIndex () {get} {set}
tagName                      Property   string tagName () {get}
tagUrn                       Property   string tagUrn () {get} {set}
textContent                  Property   Variant textContent () {get} {set}
title                        Property   string title () {get} {set}
uniqueID                     Property   string uniqueID () {get}
uniqueNumber                 Property   int uniqueNumber () {get}
xmsAcceleratorKey            Property   string xmsAcceleratorKey () {get} {s...

#>
