# http://www.pvle.be/2009/06/web-ui-automationtest-using-powershell/
# http://www.visualbasicscript.com/kickoff-javascript-inside-InternetExplorerApplication-from-vbscript-m46965.aspx
$global:ie = New-Object -com "InternetExplorer.Application"
$global:ie.Navigate("about:blank")
$global:ie.visible = $true
$global:ie.FullScreen = $true
$global:ie.Toolbar = $false
$global:ie.Menubar = $false
$global:ie.Statusbar = $false
$global:ie.AddressBar = $false
$global:ie.Resizable = $false 
$doc = $ie.Document

$doc.Body.style.cursor = "wait"

$doc.Body.InnerHTML=@"
<div style='text-align:center'>
<div id=text style='position:relative;top:41%;z-index:100;font-family:Tahoma;font-size:14pt;font-weight:bold;text-align:center;'>Message 1
<br/>
<br/>
Message 2
<br/><br/>
Message 3
<br/>
<span id='meter'>
meter should tumble here
</span>
</div>
</div>
</div>
<script type='text/javascript'>
var arrTumble = new Array('-','\\','|','/');
var objTimeout;
var counter=0;
function dummy()  {
}

function startProgress()  {
window.alert('234');
objTimeout = setTimeout('changeProgress()', 100);
}
function changeProgress() {
var objSpan = document.getElementById('meter');
if (objSpan) {
objSpan.innerHTML = arrTumble[counter];
counter=(counter+1)%4;
objTimeout = setTimeout('changeProgress()', 100);}
}
startProgress();
</script>
"@

start-sleep 4
$obj = $ie.document.parentWindow
# $obj | get-member
<#

   TypeName: mshtml.HTMLWindow2Class

Name                                          MemberType Definition
----                                          ---------- ----------
HTMLWindowEvents2_Event_onafterprint          Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onbeforeprint         Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onbeforeunload        Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onblur                Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onerror               Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onfocus               Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onhelp                Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onload                Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onresize              Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onscroll              Event      mshtml.HTMLWindowEv...
HTMLWindowEvents2_Event_onunload              Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onafterprint           Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onbeforeprint          Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onbeforeunload         Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onblur                 Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onerror                Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onfocus                Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onhelp                 Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onload                 Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onresize               Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onscroll               Event      mshtml.HTMLWindowEv...
HTMLWindowEvents_Event_onunload               Event      mshtml.HTMLWindowEv...
add_onafterprint                              Method     void add_onafterpri...
add_onbeforeprint                             Method     void add_onbeforepr...
add_onbeforeunload                            Method     void add_onbeforeun...
add_onblur                                    Method     void add_onblur(msh...
add_onerror                                   Method     void add_onerror(ms...
add_onfocus                                   Method     void add_onfocus(ms...
add_onhelp                                    Method     void add_onhelp(msh...
add_onload                                    Method     void add_onload(msh...
add_onresize                                  Method     void add_onresize(m...
add_onscroll                                  Method     void add_onscroll(m...
add_onunload                                  Method     void add_onunload(m...
alert                                         Method     void alert(string m...
attachEvent                                   Method     bool attachEvent(st...
blur                                          Method     void blur(), void D...
clearInterval                                 Method     void clearInterval(...
clearTimeout                                  Method     void clearTimeout(i...
close                                         Method     void close(), void ...
confirm                                       Method     bool confirm(string...
CreateObjRef                                  Method     System.Runtime.Remo...
createPopup                                   Method     System.Object creat...
detachEvent                                   Method     void detachEvent(st...
Equals                                        Method     bool Equals(System....
execScript                                    Method     System.Object execS...
focus                                         Method     void focus(), void ...
GetHashCode                                   Method     int GetHashCode()
GetLifetimeService                            Method     System.Object GetLi...
GetType                                       Method     type GetType()
HTMLWindowEvents2_Event_add_onafterprint      Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onbeforeprint     Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onbeforeunload    Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onblur            Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onerror           Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onfocus           Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onhelp            Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onload            Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onresize          Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onscroll          Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_add_onunload          Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onafterprint   Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onbeforeprint  Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onbeforeunload Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onblur         Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onerror        Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onfocus        Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onhelp         Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onload         Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onresize       Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onscroll       Method     void HTMLWindowEven...
HTMLWindowEvents2_Event_remove_onunload       Method     void HTMLWindowEven...
IHTMLWindow2_alert                            Method     void IHTMLWindow2_a...
IHTMLWindow2_blur                             Method     void IHTMLWindow2_b...
IHTMLWindow2_clearInterval                    Method     void IHTMLWindow2_c...
IHTMLWindow2_clearTimeout                     Method     void IHTMLWindow2_c...
IHTMLWindow2_close                            Method     void IHTMLWindow2_c...
IHTMLWindow2_confirm                          Method     bool IHTMLWindow2_c...
IHTMLWindow2_execScript                       Method     System.Object IHTML...
IHTMLWindow2_focus                            Method     void IHTMLWindow2_f...
IHTMLWindow2_item                             Method     System.Object IHTML...
IHTMLWindow2_moveBy                           Method     void IHTMLWindow2_m...
IHTMLWindow2_moveTo                           Method     void IHTMLWindow2_m...
IHTMLWindow2_navigate                         Method     void IHTMLWindow2_n...
IHTMLWindow2_open                             Method     mshtml.IHTMLWindow2...
IHTMLWindow2_prompt                           Method     System.Object IHTML...
IHTMLWindow2_resizeBy                         Method     void IHTMLWindow2_r...
IHTMLWindow2_resizeTo                         Method     void IHTMLWindow2_r...
IHTMLWindow2_scroll                           Method     void IHTMLWindow2_s...
IHTMLWindow2_scrollBy                         Method     void IHTMLWindow2_s...
IHTMLWindow2_scrollTo                         Method     void IHTMLWindow2_s...
IHTMLWindow2_showHelp                         Method     void IHTMLWindow2_s...
IHTMLWindow2_showModalDialog                  Method     System.Object IHTML...
IHTMLWindow2_toString                         Method     string IHTMLWindow2...
IHTMLWindow3_attachEvent                      Method     bool IHTMLWindow3_a...
IHTMLWindow3_detachEvent                      Method     void IHTMLWindow3_d...
IHTMLWindow3_print                            Method     void IHTMLWindow3_p...
IHTMLWindow3_showModelessDialog               Method     mshtml.IHTMLWindow2...
IHTMLWindow4_createPopup                      Method     System.Object IHTML...
InitializeLifetimeService                     Method     System.Object Initi...
item                                          Method     System.Object item(...
moveBy                                        Method     void moveBy(int x, ...
moveTo                                        Method     void moveTo(int x, ...
navigate                                      Method     void navigate(strin...
open                                          Method     mshtml.IHTMLWindow2...
print                                         Method     void print(), void ...
prompt                                        Method     System.Object promp...
remove_onafterprint                           Method     void remove_onafter...
remove_onbeforeprint                          Method     void remove_onbefor...
remove_onbeforeunload                         Method     void remove_onbefor...
remove_onblur                                 Method     void remove_onblur(...
remove_onerror                                Method     void remove_onerror...
remove_onfocus                                Method     void remove_onfocus...
remove_onhelp                                 Method     void remove_onhelp(...
remove_onload                                 Method     void remove_onload(...
remove_onresize                               Method     void remove_onresiz...
remove_onscroll                               Method     void remove_onscrol...
remove_onunload                               Method     void remove_onunloa...
resizeBy                                      Method     void resizeBy(int x...
resizeTo                                      Method     void resizeTo(int x...
scroll                                        Method     void scroll(int x, ...
scrollBy                                      Method     void scrollBy(int x...
scrollTo                                      Method     void scrollTo(int x...
setInterval                                   Method     int setInterval([re...
setTimeout                                    Method     int setTimeout([ref...
showHelp                                      Method     void showHelp(strin...
showModalDialog                               Method     System.Object showM...
showModelessDialog                            Method     mshtml.IHTMLWindow2...
toString                                      Method     string toString(), ...
clientInformation                             Property   mshtml.HTMLNavigato...
clipboardData                                 Property   mshtml.IHTMLDataTra...
closed                                        Property   bool closed {get;}
defaultStatus                                 Property   string defaultStatu...
document                                      Property   mshtml.IHTMLDocumen...
event                                         Property   mshtml.IHTMLEventOb...
external                                      Property   System.Object exter...
frameElement                                  Property   mshtml.IHTMLFrameBa...
frames                                        Property   mshtml.FramesCollec...
history                                       Property   mshtml.HTMLHistory ...
IHTMLWindow2_clientInformation                Property   mshtml.HTMLNavigato...
IHTMLWindow2_closed                           Property   bool IHTMLWindow2_c...
IHTMLWindow2_defaultStatus                    Property   string IHTMLWindow2...
IHTMLWindow2_document                         Property   mshtml.IHTMLDocumen...
IHTMLWindow2_event                            Property   mshtml.IHTMLEventOb...
IHTMLWindow2_external                         Property   System.Object IHTML...
IHTMLWindow2_frames                           Property   mshtml.FramesCollec...
IHTMLWindow2_history                          Property   mshtml.HTMLHistory ...
IHTMLWindow2_Image                            Property   mshtml.HTMLImageEle...
IHTMLWindow2_length                           Property   int IHTMLWindow2_le...
IHTMLWindow2_location                         Property   mshtml.HTMLLocation...
IHTMLWindow2_name                             Property   string IHTMLWindow2...
IHTMLWindow2_navigator                        Property   mshtml.HTMLNavigato...
IHTMLWindow2_offscreenBuffering               Property   System.Object IHTML...
IHTMLWindow2_onbeforeunload                   Property   System.Object IHTML...
IHTMLWindow2_onblur                           Property   System.Object IHTML...
IHTMLWindow2_onerror                          Property   System.Object IHTML...
IHTMLWindow2_onfocus                          Property   System.Object IHTML...
IHTMLWindow2_onhelp                           Property   System.Object IHTML...
IHTMLWindow2_onload                           Property   System.Object IHTML...
IHTMLWindow2_onresize                         Property   System.Object IHTML...
IHTMLWindow2_onscroll                         Property   System.Object IHTML...
IHTMLWindow2_onunload                         Property   System.Object IHTML...
IHTMLWindow2_opener                           Property   System.Object IHTML...
IHTMLWindow2_Option                           Property   mshtml.HTMLOptionEl...
IHTMLWindow2_parent                           Property   mshtml.IHTMLWindow2...
IHTMLWindow2_screen                           Property   mshtml.IHTMLScreen ...
IHTMLWindow2_self                             Property   mshtml.IHTMLWindow2...
IHTMLWindow2_status                           Property   string IHTMLWindow2...
IHTMLWindow2_top                              Property   mshtml.IHTMLWindow2...
IHTMLWindow2_window                           Property   mshtml.IHTMLWindow2...
IHTMLWindow2__newEnum                         Property   System.Object IHTML...
IHTMLWindow3_clipboardData                    Property   mshtml.IHTMLDataTra...
IHTMLWindow3_onafterprint                     Property   System.Object IHTML...
IHTMLWindow3_onbeforeprint                    Property   System.Object IHTML...
IHTMLWindow3_screenLeft                       Property   int IHTMLWindow3_sc...
IHTMLWindow3_screenTop                        Property   int IHTMLWindow3_sc...
IHTMLWindow4_frameElement                     Property   mshtml.IHTMLFrameBa...
Image                                         Property   mshtml.HTMLImageEle...
length                                        Property   int length {get;}
location                                      Property   mshtml.HTMLLocation...
name                                          Property   string name {get;set;}
navigator                                     Property   mshtml.HTMLNavigato...
offscreenBuffering                            Property   System.Object offsc...
onafterprint                                  Property   System.Object onaft...
onbeforeprint                                 Property   System.Object onbef...
onbeforeunload                                Property   System.Object onbef...
onblur                                        Property   System.Object onblu...
onerror                                       Property   System.Object onerr...
onfocus                                       Property   System.Object onfoc...
onhelp                                        Property   System.Object onhel...
onload                                        Property   System.Object onloa...
onresize                                      Property   System.Object onres...
onscroll                                      Property   System.Object onscr...
onunload                                      Property   System.Object onunl...
opener                                        Property   System.Object opene...
Option                                        Property   mshtml.HTMLOptionEl...
parent                                        Property   mshtml.IHTMLWindow2...
screen                                        Property   mshtml.IHTMLScreen ...
screenLeft                                    Property   int screenLeft {get;}
screenTop                                     Property   int screenTop {get;}
self                                          Property   mshtml.IHTMLWindow2...
status                                        Property   string status {get;...
top                                           Property   mshtml.IHTMLWindow2...
window                                        Property   mshtml.IHTMLWindow2...
_newEnum                                      Property   System.Object _newE...

#>
$ie.document.parentWindow.execScript("dummy")

start-sleep 10
$global:ie.Quit()